export const audioMap = {
  "John wants to cover his bedroom floor with cool new square tiles.": "/assets/audio/audio_john_wants_to_cover_his_bedroom_floor_with_cool_ne.mp3",
  "If his room is a big square, how many tiles will he need? Let's find out about area!": "/assets/audio/audio_if_his_room_is_a_big_square_how_many_tiles_will_he.mp3",
  "John is waiting at the station. He looks down at the floor and notices the beautiful square tiles. Wow, if I count the tiles in a square, I can find its area! he says.": "/assets/audio/audio_john_is_waiting_at_the_station_he_looks_down_at_th.mp3",
  "Sarah looks at a giant square window. It's divided into smaller square glass panes. If the window has 3 panes across and 3 down, there are 9 panes total! she calculates.": "/assets/audio/audio_sarah_looks_at_a_giant_square_window_it_s_divided.mp3",
  "Mike is drawing pixel art on his computer. Every character is made of tiny squares! A 4 by 4 pixel block takes 16 squares to fill, Mike explains to his friends.": "/assets/audio/audio_mike_is_drawing_pixel_art_on_his_computer_every_ch.mp3",
  "Emma weaves a cozy carpet using square patches. If I want an area of 25, I need a side length of 5 patches! she realizes. She carefully stitches them together.": "/assets/audio/audio_emma_weaves_a_cozy_carpet_using_square_patches_if.mp3",
  "John, Sarah, Mike, and Emma reunite. They discovered that area is everywhere! Now it's your turn to measure the world around you using squares!": "/assets/audio/audio_john_sarah_mike_and_emma_reunite_they_discovered_t.mp3",
  "Tap the glowing dots in order to draw a square!": "/assets/audio/audio_tap_the_glowing_dots_in_order_to_draw_a_square.mp3",
  "Tap the tiles to paint a square with the target area!": "/assets/audio/audio_tap_the_tiles_to_paint_a_square_with_the_target_ar.mp3",
  "Tap every tile inside the square to find its area!": "/assets/audio/audio_tap_every_tile_inside_the_square_to_find_its_area.mp3",
  "Amazing! You found the shape's secret! You're a geometry star!": "/assets/audio/audio_amazing_you_found_the_shape_s_secret_you_re_a_geom.mp3",
  "Not quite! Let's look at this shape again.": "/assets/audio/audio_not_quite_let_s_look_at_this_shape_again.mp3",
  "Let's count together!": "/assets/audio/audio_let_s_count_together.mp3",
  "What a journey around the world! Can you find a square in your own room and calculate its area?": "/assets/audio/audio_what_a_journey_around_the_world_can_you_find_a_squ.mp3",
  "Lesson complete! You are an Area of Squares Champion!": "/assets/audio/audio_lesson_complete_you_are_an_area_of_squares_champio.mp3",
  "If a square courtyard is made of 2 rows of 2 tiles, what is its area?": "/assets/audio/audio_if_a_square_courtyard_is_made_of_2_rows_of_2_tiles.mp3",
  "A small square mosaic has 3 columns and 3 rows. How many total tiles (area) is it?": "/assets/audio/audio_a_small_square_mosaic_has_3_columns_and_3_rows_how.mp3",
  "What do we call the total space covered by the tiles inside a square?": "/assets/audio/audio_what_do_we_call_the_total_space_covered_by_the_til.mp3",
  "If a square has side length of 1 unit, what is its area?": "/assets/audio/audio_if_a_square_has_side_length_of_1_unit_what_is_its.mp3",
  "If we double the side length of a 1x1 square to 2x2, what happens to its area?": "/assets/audio/audio_if_we_double_the_side_length_of_a_1x1_square_to_2x.mp3",
  "A pixel art block is a square with side length 4. What is its area?": "/assets/audio/audio_a_pixel_art_block_is_a_square_with_side_length_4_w.mp3",
  "If a square window pane has a side of 5 units, what is its area?": "/assets/audio/audio_if_a_square_window_pane_has_a_side_of_5_units_what.mp3",
  "Which formula is correct for finding the Area of a Square?": "/assets/audio/audio_which_formula_is_correct_for_finding_the_area_of_a.mp3",
  "If a square has side length of 6, what is its area?": "/assets/audio/audio_if_a_square_has_side_length_of_6_what_is_its_area.mp3",
  "What is the area of a square with a side length of 7?": "/assets/audio/audio_what_is_the_area_of_a_square_with_a_side_length_of.mp3",
  "A square plaza in Grid City has an area of 100 square blocks. What is its side length?": "/assets/audio/audio_a_square_plaza_in_grid_city_has_an_area_of_100_squ.mp3",
  "If a square carpet has an area of 64 square units, how long is one side?": "/assets/audio/audio_if_a_square_carpet_has_an_area_of_64_square_units.mp3",
  "Which square has the largest area?": "/assets/audio/audio_which_square_has_the_largest_area.mp3",
  "If you have 81 small square tiles, can you make a perfect large square?": "/assets/audio/audio_if_you_have_81_small_square_tiles_can_you_make_a_p.mp3",
  "A perfect square with a side of 10 has an area of...": "/assets/audio/audio_a_perfect_square_with_a_side_of_10_has_an_area_of.mp3"
};
