export const audioMap = {
  "John is building a kite for the Tokyo Kite Festival.": "/assets/audio/audio_john_is_building_a_kite_for_the_tokyo_kite_festiva.mp3",
  "Its frame needs two sticks that never cross, no matter how far they stretch.": "/assets/audio/audio_its_frame_needs_two_sticks_that_never_cross_no_mat.mp3",
  "What kind of lines does John need? Let's find out!": "/assets/audio/audio_what_kind_of_lines_does_john_need_let_s_find_out.mp3",
  "John waits at the station. The Global Shapes Express only stops at stations that follow shapes! Every door, every window, every arch around us is a shape, the conductor says.": "/assets/audio/audio_john_waits_at_the_station_the_global_shapes_expres.mp3",
  "Sarah arrives in London. She notices Big Ben's huge circular clock face. The windows in the buildings are squares. A circle is perfectly round with no corners, says Sarah.": "/assets/audio/audio_sarah_arrives_in_london_she_notices_big_ben_s_huge.mp3",
  "Mike visits a pagoda in Tokyo. Every roof is a triangle! Even Mount Fuji in the distance is a giant triangle shape. A triangle has 3 sides and 3 corners, Mike says proudly.": "/assets/audio/audio_mike_visits_a_pagoda_in_tokyo_every_roof_is_a_tria.mp3",
  "Emma stands before the Pyramids in Egypt. Each face of a pyramid is a giant triangle! The ancient Egyptians used triangle shapes to build structures that last thousands of years! Emma gasps.": "/assets/audio/audio_emma_stands_before_the_pyramids_in_egypt_each_face.mp3",
  "John, Sarah, Mike, and Emma reunite at the final station. They discovered circles, squares, triangles, and rectangles everywhere they went. Now it's your turn to find shapes in the world around you!": "/assets/audio/audio_john_sarah_mike_and_emma_reunite_at_the_final_stat.mp3",
  "Tap two lines and tell me — are they parallel, perpendicular, or neither?": "/assets/audio/audio_tap_two_lines_and_tell_me_are_they_parallel_perpen.mp3",
  "Look at the angle. Is it a right angle, an acute angle, or an obtuse angle?": "/assets/audio/audio_look_at_the_angle_is_it_a_right_angle_an_acute_ang.mp3",
  "Look at the shape. How many sides does it have?": "/assets/audio/audio_look_at_the_shape_how_many_sides_does_it_have.mp3",
  "Amazing! You found the shape's secret! You're a geometry star!": "/assets/audio/audio_amazing_you_found_the_shape_s_secret_you_re_a_geom.mp3",
  "Not quite! Let's look at this shape again.": "/assets/audio/audio_not_quite_let_s_look_at_this_shape_again.mp3",
  "Let's count together!": "/assets/audio/audio_let_s_count_together.mp3",
  "What a journey around the world! Can you find a right angle in your own room?": "/assets/audio/audio_what_a_journey_around_the_world_can_you_find_a_rig.mp3",
  "Lesson complete! You are a Global Shape Quest Champion!": "/assets/audio/audio_lesson_complete_you_are_a_global_shape_quest_champ.mp3",
  "Look at the railway tracks. Are they parallel, perpendicular, or neither?": "/assets/audio/audio_look_at_the_railway_tracks_are_they_parallel_perpe.mp3",
  "Look at the window grid. Are the crossing lines parallel, perpendicular, or neither?": "/assets/audio/audio_look_at_the_window_grid_are_the_crossing_lines_par.mp3",
  "Look at the bridge cables. Are they parallel, perpendicular, or neither?": "/assets/audio/audio_look_at_the_bridge_cables_are_they_parallel_perpen.mp3",
  "Look at the road crossing. Are the lines parallel, perpendicular, or neither?": "/assets/audio/audio_look_at_the_road_crossing_are_the_lines_parallel_p.mp3",
  "Look at the fence posts. Are they parallel, perpendicular, or neither?": "/assets/audio/audio_look_at_the_fence_posts_are_they_parallel_perpendi.mp3",
  "Is the corner of this book a right angle, an acute angle, or an obtuse angle?": "/assets/audio/audio_is_the_corner_of_this_book_a_right_angle_an_acute.mp3",
  "Is the tip of this pizza slice a right angle, an acute angle, or an obtuse angle?": "/assets/audio/audio_is_the_tip_of_this_pizza_slice_a_right_angle_an_ac.mp3",
  "Is the roof of this house a right angle, an acute angle, or an obtuse angle?": "/assets/audio/audio_is_the_roof_of_this_house_a_right_angle_an_acute_a.mp3",
  "Is the corner of a square a right angle, an acute angle, or an obtuse angle?": "/assets/audio/audio_is_the_corner_of_a_square_a_right_angle_an_acute_a.mp3",
  "Is the point of this star a right angle, an acute angle, or an obtuse angle?": "/assets/audio/audio_is_the_point_of_this_star_a_right_angle_an_acute_a.mp3",
  "This shape has 3 sides and 3 corners. What is it called?": "/assets/audio/audio_this_shape_has_3_sides_and_3_corners_what_is_it_ca.mp3",
  "This shape has 4 equal sides and 4 right angles. What is it called?": "/assets/audio/audio_this_shape_has_4_equal_sides_and_4_right_angles_wh.mp3",
  "This shape has 5 sides and 5 corners. What is it called?": "/assets/audio/audio_this_shape_has_5_sides_and_5_corners_what_is_it_ca.mp3",
  "This shape has 6 sides and 6 corners. What is it called?": "/assets/audio/audio_this_shape_has_6_sides_and_6_corners_what_is_it_ca.mp3",
  "This shape has 4 sides, but only the opposite sides are equal. What is it called?": "/assets/audio/audio_this_shape_has_4_sides_but_only_the_opposite_sides.mp3"
};
